#                                                         -*- coding: utf-8 -*-
#! \file    ./fmtviewer/texdefs.rb
#! \author  Jiří Kučera, <sanczes@gmail.com>
#! \stamp   2014-08-20 22:47:43 (UTC+01:00, DST+01:00)
#! \project textools: Utilities for debugging TeX/LaTeX output.
#! \license MIT
#! \version 0.1.0
#! \fdesc   TeX/pdfTeX constants/macros definitions.
#

require './cpascal'

module PdfTeX

  module Defs

    S_ETEX_VERSION = "2.5"
    S_PDFTEX_VERSION = "1.40.14"
    S_BANNER = \
      "This is pdfTeX, Version 3.1415926-#{S_ETEX_VERSION}-#{S_PDFTEX_VERSION}"
    S_WEB2CVERSION = " (TeX Live 2013)"
    S_KPSEVERSION = "kpathsea version 6.1.1"
    PDFTEX = 'pdftex'
    TEXMF_POOL_NAME = 'pdftex.pool'
    TEXMF_ENGINE_NAME = 'pdftex'

    # {2*}:
    ETEX_VERSION = 2
    ETEX_REVISION = ".5"
    ETEX_VERSION_STRING = "-2.5"
    ETEX_BANNER = "This is e-TeX, Version 3.1415926" \
                + ETEX_VERSION_STRING
    PDFTEX_VERSION = 140
    PDFTEX_REVISION = "14"
    PDFTEX_VERSION_STRING = "-1.40.14"
    PDFTEX_BANNER = "This is pdfTeX, Version 3.1415926" \
                  + ETEX_VERSION_STRING \
                  + PDFTEX_VERSION_STRING
    TEX_BANNER_K = "This is TeXk, Version 3.1415926"
    TEX_BANNER = "This is TeX, Version 3.1415926"
    BANNER = PDFTEX_BANNER
    BANNER_K = PDFTEX_BANNER
    TEX = PDFTEX
    TEXXET_CODE = 0
    ETEX_STATES = 1

    # {11*}:
    FILE_NAME_SIZE = CPascal::IntType::MAX
    SSUP_ERROR_LINE = 255
    SSUP_MAX_STRINGS = 2097151
    SSUP_TRIE_OPCODE = 65535
    SSUP_TRIE_SIZE = 0x003FFFFF
    SSUP_HYPH_SIZE = 65535
    IINF_HYPHEN_SIZE = 610
    MAX_FONT_MAX = 9000
    FONT_BASE = 0
    # --- Constants in the outer block:
    HASH_OFFSET = 514
    TRIE_OP_SIZE = 35111
    NEG_TRIE_OP_SIZE = -35111
    MIN_TRIE_OP = 0
    MAX_TRIE_OP = SSUP_TRIE_OPCODE
    POOL_NAME = TEXMF_POOL_NAME
    ENGINE_NAME = TEXMF_ENGINE_NAME
    INF_MEM_BOT = 0
    SUP_MEM_BOT = 1
    INF_MAIN_MEMORY = 3000
    SUP_MAIN_MEMORY = 256000000
    INF_TRIE_SIZE = 8000
    SUP_TRIE_SIZE = SSUP_TRIE_SIZE
    INF_MAX_STRINGS = 3000
    SUP_MAX_STRINGS = SSUP_MAX_STRINGS
    INF_STRINGS_FREE = 100
    SUP_STRINGS_FREE = SUP_MAX_STRINGS
    INF_BUF_SIZE = 500
    SUP_BUF_SIZE = 30000000
    INF_NEST_SIZE = 40
    SUP_NEST_SIZE = 4000
    INF_MAX_IN_OPEN = 6
    SUP_MAX_IN_OPEN = 127
    INF_PARAM_SIZE = 60
    SUP_PARAM_SIZE = 32767
    INF_SAVE_SIZE = 600
    SUP_SAVE_SIZE = 80000
    INF_STACK_SIZE = 200
    SUP_STACK_SIZE = 30000
    INF_DVI_BUF_SIZE = 800
    SUP_DVI_BUF_SIZE = 65536
    INF_FONT_MEM_SIZE = 20000
    SUP_FONT_MEM_SIZE = 147483647
    SUP_FONT_MAX = MAX_FONT_MAX
    INF_FONT_MAX = 50
    INF_POOL_SIZE = 32000
    SUP_POOL_SIZE = 40000000
    INF_POOL_FREE = 1000
    SUP_POOL_FREE = SUP_POOL_SIZE
    INF_STRING_VACANCIES = 8000
    SUP_STRING_VACANCIES = SUP_POOL_SIZE - 23000
    SUP_HASH_EXTRA = SUP_MAX_STRINGS
    INF_HASH_EXTRA = 0
    SUP_HYPH_SIZE = SSUP_HYPH_SIZE
    INF_HYPH_SIZE = IINF_HYPHEN_SIZE
    INF_EXPAND_DEPTH = 10
    SUP_EXPAND_DEPTH = 10000000

    # {12*}:
    HASH_SIZE = 15000
    HASH_PRIME = 8501
    HYPH_PRIME = 607

    # {16*}:
    EMPTY = 0

    # {19*}:
    FIRST_TEXT_CHAR = 0
    LAST_TEXT_CHAR = 255

    # {22}:
    NULL_CODE = 0
    CARRIAGE_RETURN = 015
    INVALID_CODE = 0177

    # {54*}:
    NO_PRINT = 16
    TERM_ONLY = 17
    LOG_ONLY = 18
    TERM_AND_LOG = 19
    PSEUDO = 20
    NEW_STRING = 21
    MAX_SELECTOR = 21

    # {73*}:
    BATCH_MODE = 0
    NONSTOP_MODE = 1
    SCROLL_MODE = 2
    ERROR_STOP_MODE = 3
    UNSPECIFIED_MODE = 4

    # {76}:
    SPOTLESS = 0
    WARNING_ISSUED = 1
    ERROR_MESSAGE_ISSUED = 2
    FATAL_ERROR_STOP = 3

    # {101}:
    UNITY = 0200000
    TWO = 0400000

    # {108}:
    INF_BAD = 10000

    # {111}:
    FRACTION_HALF = 01000000000
    FRACTION_ONE = 02000000000
    FRACTION_FOUR = 010000000000
    EL_GORDO = 017777777777

    # {128*}:
    MIN_QUARTERWORD = 0
    MAX_QUARTERWORD = 255
    MIN_HALFWORD = -0x0FFFFFFF
    MAX_HALFWORD = 0x0FFFFFFF

    # {133}:
    NULL = MIN_HALFWORD

    # {142}:
    EMPTY_FLAG = MAX_HALFWORD

    # {153*}:
    SYNCTEX_FIELD_SIZE = 2
    HLIST_NODE = 0
    BOX_NODE_SIZE = 7 + SYNCTEX_FIELD_SIZE
    WIDTH_OFFSET = 1
    DEPTH_OFFSET = 2
    HEIGHT_OFFSET = 3
    LIST_OFFSET = 5
    NORMAL = 0
    STRETCHING = 1
    SHRINKING = 2
    GLUE_OFFSET = 6

    # {155}:
    VLIST_NODE = 1

    # {156*}:
    RULE_NODE = 2
    RULE_NODE_SIZE = 4 + SYNCTEX_FIELD_SIZE
    NULL_FLAG = -010000000000

    # {158}:
    INS_NODE = 3
    INS_NODE_SIZE = 5

    # {159*}:
    MARK_NODE = 4
    SMALL_NODE_SIZE = 2
    MEDIUM_NODE_SIZE = SMALL_NODE_SIZE + SYNCTEX_FIELD_SIZE

    # {160}:
    ADJUST_NODE = 5

    # {161}:
    LIGATURE_NODE = 6

    # {163}:
    DISC_NODE = 7

    # {164}:
    WHATSIT_NODE = 8

    # {165*}:
    MATH_NODE = 9
    BEFORE = 0
    AFTER = 1
    M_CODE = 2
    BEGIN_M_CODE = M_CODE + BEFORE
    END_M_CODE = M_CODE + AFTER
    L_CODE = 4
    BEGIN_L_CODE = L_CODE + BEGIN_M_CODE
    END_L_CODE = L_CODE + END_M_CODE
    R_CODE = L_CODE + L_CODE
    BEGIN_R_CODE = R_CODE + BEGIN_M_CODE
    END_R_CODE = R_CODE + END_M_CODE

    # {167}:
    GLUE_NODE = 10
    COND_MATH_GLUE = 98
    MU_GLUE = 99
    A_LEADERS = 100
    C_LEADERS = 101
    X_LEADERS = 102

    # {168}:
    GLUE_SPEC_SIZE = 4
    FIL = 1
    FILL = 2
    FILLL = 3

    # {173}:
    KERN_NODE = 11
    EXPLICIT = 1
    ACC_KERN = 2
    MARGIN_KERN_NODE = 40
    MARGIN_KERN_NODE_SIZE = 3
    LEFT_SIDE = 0
    RIGHT_SIDE = 1
    LP_CODE_BASE = 2
    RP_CODE_BASE = 3
    EF_CODE_BASE = 4
    TAG_CODE = 5
    KN_BS_CODE_BASE = 7
    ST_BS_CODE_BASE = 8
    SH_BS_CODE_BASE = 9
    KN_BC_CODE_BASE = 10
    KN_AC_CODE_BASE = 11
    AUTO_KERN = EXPLICIT
    NO_LIG_CODE = 6
    MAX_HLIST_STACK = 512

    # {175}:
    PENALTY_NODE = 12
    INF_PENALTY = INF_BAD
    EJECT_PENALTY = -INF_PENALTY

    # {177}:
    UNSET_NODE = 13

    # {180}:
    HI_MEM_STAT_USAGE = 15

    # {225}:
    ESCAPE = 0
    RELAX = 0
    LEFT_BRACE = 1
    RIGHT_BRACE = 2
    MATH_SHIFT = 3
    TAB_MARK = 4
    CAR_RET = 5
    OUT_PARAM = 5
    MAC_PARAM = 6
    SUP_MARK = 7
    SUB_MARK = 8
    IGNORE = 9
    ENDV = 9
    SPACER = 10
    LETTER = 11
    OTHER_CHAR = 12
    ACTIVE_CHAR = 13
    PAR_END = 13
    MATCH = 13
    COMMENT = 14
    END_MATCH = 14
    STOP = 14
    INVALID_CHAR = 15
    DELIM_NUM = 15
    MAX_CHAR_CODE = 15

    # {226}:
    CHAR_NUM = 16
    MATH_CHAR_NUM = 17
    MARK = 18
    XRAY = 19
    MAKE_BOX = 20
    HMOVE = 21
    VMOVE = 22
    UN_HBOX = 23
    UN_VBOX = 24
    REMOVE_ITEM = 25
    HSKIP = 26
    VSKIP = 27
    MSKIP = 28
    KERN = 29
    MKERN = 30
    LEADER_SHIP = 31
    HALIGN = 32
    VALIGN = 33
    NO_ALIGN = 34
    VRULE = 35
    HRULE = 36
    INSERT = 37
    VADJUST = 38
    IGNORE_SPACES = 39
    AFTER_ASSIGNMENT = 40
    AFTER_GROUP = 41
    BREAK_PENALTY = 42
    START_PAR = 43
    ITAL_CORR = 44
    ACCENT = 45
    MATH_ACCENT = 46
    DISCRETIONARY = 47
    EQ_NO = 48
    LEFT_RIGHT = 49
    MATH_COMP = 50
    LIMIT_SWITCH = 51
    ABOVE = 52
    MATH_STYLE = 53
    MATH_CHOICE = 54
    NON_SCRIPT = 55
    VCENTER = 56
    CASE_SHIFT = 57
    MESSAGE = 58
    EXTENSION = 59
    IN_STREAM = 60
    BEGIN_GROUP = 61
    END_GROUP = 62
    OMIT = 63
    EX_SPACE = 64
    NO_BOUNDARY = 65
    RADICAL = 66
    END_CS_NAME = 67
    MIN_INTERNAL = 68
    CHAR_GIVEN = 68
    MATH_GIVEN = 69
    LAST_ITEM = 70
    MAX_NON_PREFIXED_COMMAND = 70

    # {227*}:
    TOKS_REGISTER = 71
    ASSIGN_TOKS = 72
    ASSIGN_INT = 73
    ASSIGN_DIMEN = 74
    ASSIGN_GLUE = 75
    ASSIGN_MU_GLUE = 76
    ASSIGN_FONT_DIMEN = 77
    ASSIGN_FONT_INT = 78
    SET_AUX = 79
    SET_PREV_GRAF = 80
    SET_PAGE_DIMEN = 81
    SET_PAGE_INT = 82
    SET_BOX_DIMEN = 83
    SET_SHAPE = 84
    DEF_CODE = 85
    DEF_FAMILY = 86
    SET_FONT = 87
    DEF_FONT = 88
    REGISTER = 89
    MAX_INTERNAL = 89
    ADVANCE = 90
    MULTIPLY = 91
    DIVIDE = 92
    PREFIX = 93
    LET = 94
    SHORTHAND_DEF = 95
    READ_TO_CS = 96
    DEF = 97
    SET_BOX = 98
    HYPH_DATA = 99
    SET_INTERACTION = 100
    LETTERSPACE_FONT = 101
    PDF_COPY_FONT = 102
    MAX_COMMAND = 102

    # {228}:
    UNDEFINED_CS = MAX_COMMAND + 1
    EXPAND_AFTER = MAX_COMMAND + 2
    NO_EXPAND = MAX_COMMAND + 3
    INPUT = MAX_COMMAND + 4
    IF_TEST = MAX_COMMAND + 5
    FI_OR_ELSE = MAX_COMMAND + 6
    CS_NAME = MAX_COMMAND + 7
    CONVERT = MAX_COMMAND + 8
    THE = MAX_COMMAND + 9
    TOP_BOT_MARK = MAX_COMMAND + 10
    CALL = MAX_COMMAND + 11
    LONG_CALL = MAX_COMMAND + 12
    OUTER_CALL = MAX_COMMAND + 13
    LONG_OUTER_CALL = MAX_COMMAND + 14
    END_TEMPLATE = MAX_COMMAND + 15
    DONT_EXPAND = MAX_COMMAND + 16
    GLUE_REF = MAX_COMMAND + 17
    SHAPE_REF = MAX_COMMAND + 18
    BOX_REF = MAX_COMMAND + 19
    DATA = MAX_COMMAND + 20

    # {229*}:
    VMODE = 1
    HMODE = VMODE + MAX_COMMAND + 1
    MMODE = HMODE + MAX_COMMAND + 1

    # {230}:
    IGNORE_DEPTH = -65536000

    # {239}:
    LEVEL_ZERO = MIN_QUARTERWORD
    LEVEL_ONE = LEVEL_ZERO + 1

    # {240*}:
    ACTIVE_BASE = 1
    SINGLE_BASE = ACTIVE_BASE + 256
    NULL_CS = SINGLE_BASE + 256
    HASH_BASE = NULL_CS + 1
    FROZEN_CONTROL_SEQUENCE = HASH_BASE + HASH_SIZE
    FROZEN_PROTECTION = FROZEN_CONTROL_SEQUENCE
    FROZEN_CR = FROZEN_CONTROL_SEQUENCE + 1
    FROZEN_END_GROUP = FROZEN_CONTROL_SEQUENCE + 2
    FROZEN_RIGHT = FROZEN_CONTROL_SEQUENCE + 3
    FROZEN_FI = FROZEN_CONTROL_SEQUENCE + 4
    FROZEN_END_TEMPLATE = FROZEN_CONTROL_SEQUENCE + 5
    FROZEN_ENDV = FROZEN_CONTROL_SEQUENCE + 6
    FROZEN_RELAX = FROZEN_CONTROL_SEQUENCE + 7
    END_WRITE = FROZEN_CONTROL_SEQUENCE + 8
    FROZEN_DONT_EXPAND = FROZEN_CONTROL_SEQUENCE + 9
    FROZEN_SPECIAL = FROZEN_CONTROL_SEQUENCE + 10
    FROZEN_NULL_FONT = FROZEN_CONTROL_SEQUENCE + 12
    FROZEN_PRIMITIVE = FROZEN_CONTROL_SEQUENCE + 11
    FONT_ID_BASE = FROZEN_NULL_FONT - FONT_BASE
    UNDEFINED_CONTROL_SEQUENCE = FROZEN_NULL_FONT + MAX_FONT_MAX + 1
    GLUE_BASE = UNDEFINED_CONTROL_SEQUENCE + 1

    # {242*}:
    LINE_SKIP_CODE = 0
    BASELINE_SKIP_CODE = 1
    PAR_SKIP_CODE = 2
    ABOVE_DISPLAY_SKIP_CODE = 3
    BELOW_DISPLAY_SKIP_CODE = 4
    ABOVE_DISPLAY_SHORT_SKIP_CODE = 5
    BELOW_DISPLAY_SHORT_SKIP_CODE = 6
    LEFT_SKIP_CODE = 7
    RIGHT_SKIP_CODE = 8
    TOP_SKIP_CODE = 9
    SPLIT_TOP_SKIP_CODE = 10
    TAB_SKIP_CODE = 11
    SPACE_SKIP_CODE = 12
    XSPACE_SKIP_CODE = 13
    PAR_FILL_SKIP_CODE = 14
    THIN_MU_SKIP_CODE = 15
    MED_MU_SKIP_CODE = 16
    THICK_MU_SKIP_CODE = 17
    GLUE_PARS = 18
    SKIP_BASE = GLUE_BASE + GLUE_PARS
    MU_SKIP_BASE = SKIP_BASE + 256
    LOCAL_BASE = MU_SKIP_BASE + 256

    # {248*}:
    PAR_SHAPE_LOC = LOCAL_BASE
    OUTPUT_ROUTINE_LOC = LOCAL_BASE + 1
    EVERY_PAR_LOC = LOCAL_BASE + 2
    EVERY_MATH_LOC = LOCAL_BASE + 3
    EVERY_DISPLAY_LOC = LOCAL_BASE + 4
    EVERY_HBOX_LOC = LOCAL_BASE + 5
    EVERY_VBOX_LOC = LOCAL_BASE + 6
    EVERY_JOB_LOC = LOCAL_BASE + 7
    EVERY_CR_LOC = LOCAL_BASE + 8
    ERR_HELP_LOC = LOCAL_BASE + 9
    TEX_TOKS = LOCAL_BASE + 10
    PDFTEX_FIRST_LOC = TEX_TOKS
    PDF_PAGES_ATTR_LOC = PDFTEX_FIRST_LOC + 0
    PDF_PAGE_ATTR_LOC = PDFTEX_FIRST_LOC + 1
    PDF_PAGE_RESOURCES_LOC = PDFTEX_FIRST_LOC + 2
    PDF_PK_MODE_LOC = PDFTEX_FIRST_LOC + 3
    PDF_TOKS = PDFTEX_FIRST_LOC + 4
    ETEX_TOKS_BASE = PDF_TOKS
    EVERY_EOF_LOC = ETEX_TOKS_BASE
    ETEX_TOKS = ETEX_TOKS_BASE + 1
    TOKS_BASE = ETEX_TOKS
    ETEX_PEN_BASE = TOKS_BASE + 256
    INTER_LINE_PENALTIES_LOC = ETEX_PEN_BASE
    CLUB_PENALTIES_LOC = ETEX_PEN_BASE + 1
    WIDOW_PENALTIES_LOC = ETEX_PEN_BASE + 2
    DISPLAY_WIDOW_PENALTIES_LOC = ETEX_PEN_BASE + 3
    ETEX_PENS = ETEX_PEN_BASE + 4
    BOX_BASE = ETEX_PENS
    CUR_FONT_LOC = BOX_BASE + 256
    XORD_CODE_BASE = CUR_FONT_LOC + 1
    XCHR_CODE_BASE = XORD_CODE_BASE + 1
    XPRN_CODE_BASE = XCHR_CODE_BASE + 1
    MATH_FONT_BASE = XPRN_CODE_BASE + 1
    CAT_CODE_BASE = MATH_FONT_BASE + 48
    LC_CODE_BASE = CAT_CODE_BASE + 256
    UC_CODE_BASE = LC_CODE_BASE + 256
    SF_CODE_BASE = UC_CODE_BASE + 256
    MATH_CODE_BASE = SF_CODE_BASE + 256
    CHAR_SUB_CODE_BASE = MATH_CODE_BASE + 256
    INT_BASE = CHAR_SUB_CODE_BASE + 256

    # {250}:
    NULL_FONT = FONT_BASE
    VAR_CODE = 070000

    # {254*}:
    PRETOLERANCE_CODE = 0
    TOLERANCE_CODE = 1
    LINE_PENALTY_CODE = 2
    HYPHEN_PENALTY_CODE = 3
    EX_HYPHEN_PENALTY_CODE = 4
    CLUB_PENALTY_CODE = 5
    WIDOW_PENALTY_CODE = 6
    DISPLAY_WIDOW_PENALTY_CODE = 7
    BROKEN_PENALTY_CODE = 8
    BIN_OP_PENALTY_CODE = 9
    REL_PENALTY_CODE = 10
    PRE_DISPLAY_PENALTY_CODE = 11
    POST_DISPLAY_PENALTY_CODE = 12
    INTER_LINE_PENALTY_CODE = 13
    DOUBLE_HYPHEN_DEMERITS_CODE = 14
    FINAL_HYPHEN_DEMERITS_CODE = 15
    ADJ_DEMERITS_CODE = 16
    MAG_CODE = 17
    DELIMITER_FACTOR_CODE = 18
    LOOSENESS_CODE = 19
    TIME_CODE = 20
    DAY_CODE = 21
    MONTH_CODE = 22
    YEAR_CODE = 23
    SHOW_BOX_BREADTH_CODE = 24
    SHOW_BOX_DEPTH_CODE = 25
    HBADNESS_CODE = 26
    VBADNESS_CODE = 27
    PAUSING_CODE = 28
    TRACING_ONLINE_CODE = 29
    TRACING_MACROS_CODE = 30
    TRACING_STATS_CODE = 31
    TRACING_PARAGRAPHS_CODE = 32
    TRACING_PAGES_CODE = 33
    TRACING_OUTPUT_CODE = 34
    TRACING_LOST_CHARS_CODE = 35
    TRACING_COMMANDS_CODE = 36
    TRACING_RESTORES_CODE = 37
    UC_HYPH_CODE = 38
    OUTPUT_PENALTY_CODE = 39
    MAX_DEAD_CYCLES_CODE = 40
    HANG_AFTER_CODE = 41
    FLOATING_PENALTY_CODE = 42
    GLOBAL_DEFS_CODE = 43
    CUR_FAM_CODE = 44
    ESCAPE_CHAR_CODE = 45
    DEFAULT_HYPHEN_CHAR_CODE = 46
    DEFAULT_SKEW_CHAR_CODE = 47
    END_LINE_CHAR_CODE = 48
    NEW_LINE_CHAR_CODE = 49
    LANGUAGE_CODE = 50
    LEFT_HYPHEN_MIN_CODE = 51
    RIGHT_HYPHEN_MIN_CODE = 52
    HOLDING_INSERTS_CODE = 53
    ERROR_CONTEXT_LINES_CODE = 54
    TEX_INT_PARS = 55
    WEB2C_INT_BASE = TEX_INT_PARS
    CHAR_SUB_DEF_MIN_CODE = WEB2C_INT_BASE
    CHAR_SUB_DEF_MAX_CODE = WEB2C_INT_BASE + 1
    TRACING_CHAR_SUB_DEF_CODE = WEB2C_INT_BASE + 2
    MUBYTE_IN_CODE = WEB2C_INT_BASE + 3
    MUBYTE_OUT_CODE = WEB2C_INT_BASE + 4
    MUBYTE_LOG_CODE = WEB2C_INT_BASE + 5
    SPEC_OUT_CODE = WEB2C_INT_BASE + 6
    WEB2C_INT_PARS = WEB2C_INT_BASE + 7
    PDFTEX_FIRST_INTEGER_CODE = WEB2C_INT_PARS
    PDF_OUTPUT_CODE = PDFTEX_FIRST_INTEGER_CODE + 0
    PDF_COMPRESS_LEVEL_CODE = PDFTEX_FIRST_INTEGER_CODE + 1
    PDF_DECIMAL_DIGITS_CODE = PDFTEX_FIRST_INTEGER_CODE + 2
    PDF_MOVE_CHARS_CODE = PDFTEX_FIRST_INTEGER_CODE + 3
    PDF_IMAGE_RESOLUTION_CODE = PDFTEX_FIRST_INTEGER_CODE + 4
    PDF_PK_RESOLUTION_CODE = PDFTEX_FIRST_INTEGER_CODE + 5
    PDF_UNIQUE_RESNAME_CODE = PDFTEX_FIRST_INTEGER_CODE + 6
    PDF_OPTION_ALWAYS_USE_PDFPAGEBOX_CODE = PDFTEX_FIRST_INTEGER_CODE + 7
    PDF_OPTION_PDF_INCLUSION_ERRORLEVEL_CODE = PDFTEX_FIRST_INTEGER_CODE + 8
    PDF_MINOR_VERSION_CODE = PDFTEX_FIRST_INTEGER_CODE + 9
    PDF_FORCE_PAGEBOX_CODE = PDFTEX_FIRST_INTEGER_CODE + 10
    PDF_PAGEBOX_CODE = PDFTEX_FIRST_INTEGER_CODE + 11
    PDF_INCLUSION_ERRORLEVEL_CODE = PDFTEX_FIRST_INTEGER_CODE + 12
    PDF_GAMMA_CODE = PDFTEX_FIRST_INTEGER_CODE + 13
    PDF_IMAGE_GAMMA_CODE = PDFTEX_FIRST_INTEGER_CODE + 14
    PDF_IMAGE_HICOLOR_CODE = PDFTEX_FIRST_INTEGER_CODE + 15
    PDF_IMAGE_APPLY_GAMMA_CODE = PDFTEX_FIRST_INTEGER_CODE + 16
    PDF_ADJUST_SPACING_CODE = PDFTEX_FIRST_INTEGER_CODE + 17
    PDF_PROTRUDE_CHARS_CODE = PDFTEX_FIRST_INTEGER_CODE + 18
    PDF_TRACING_FONTS_CODE = PDFTEX_FIRST_INTEGER_CODE + 19
    PDF_OBJCOMPRESSLEVEL_CODE = PDFTEX_FIRST_INTEGER_CODE + 20
    PDF_ADJUST_INTERWORD_GLUE_CODE = PDFTEX_FIRST_INTEGER_CODE + 21
    PDF_PREPEND_KERN_CODE = PDFTEX_FIRST_INTEGER_CODE + 22
    PDF_APPEND_KERN_CODE = PDFTEX_FIRST_INTEGER_CODE + 23
    PDF_GEN_TOUNICODE_CODE = PDFTEX_FIRST_INTEGER_CODE + 24
    PDF_DRAFTMODE_CODE = PDFTEX_FIRST_INTEGER_CODE + 25
    PDF_INCLUSION_COPY_FONT_CODE = PDFTEX_FIRST_INTEGER_CODE + 26
    PDF_SUPPRESS_WARNING_DUP_DEST_CODE = PDFTEX_FIRST_INTEGER_CODE + 27
    PDF_SUPPRESS_WARNING_DUP_MAP_CODE = PDFTEX_FIRST_INTEGER_CODE + 28
    PDF_INT_PARS = PDFTEX_FIRST_INTEGER_CODE + 29
    ETEX_INT_BASE = PDF_INT_PARS
    TRACING_ASSIGNS_CODE = ETEX_INT_BASE
    TRACING_GROUPS_CODE = ETEX_INT_BASE + 1
    TRACING_IFS_CODE = ETEX_INT_BASE + 2
    TRACING_SCAN_TOKENS_CODE = ETEX_INT_BASE + 3
    TRACING_NESTING_CODE = ETEX_INT_BASE + 4
    PRE_DISPLAY_DIRECTION_CODE = ETEX_INT_BASE + 5
    LAST_LINE_FIT_CODE = ETEX_INT_BASE + 6
    SAVING_VDISCARDS_CODE = ETEX_INT_BASE + 7
    SAVING_HYPH_CODES_CODE = ETEX_INT_BASE + 8
    ETEX_STATE_CODE = ETEX_INT_BASE + 9
    ETEX_INT_PARS = ETEX_STATE_CODE + ETEX_STATES
    SYNCTEX_CODE = ETEX_INT_PARS
    INT_PARS = SYNCTEX_CODE + 1
    COUNT_BASE = INT_BASE + INT_PARS
    DEL_CODE_BASE = COUNT_BASE + 256
    DIMEN_BASE = DEL_CODE_BASE + 256

    # {265}:
    PAR_INDENT_CODE = 0
    MATH_SURROUND_CODE = 1
    LINE_SKIP_LIMIT_CODE = 2
    HSIZE_CODE = 3
    VSIZE_CODE = 4
    MAX_DEPTH_CODE = 5
    SPLIT_MAX_DEPTH_CODE = 6
    BOX_MAX_DEPTH_CODE = 7
    HFUZZ_CODE = 8
    VFUZZ_CODE = 9
    DELIMITER_SHORTFALL_CODE = 10
    NULL_DELIMITER_SPACE_CODE = 11
    SCRIPT_SPACE_CODE = 12
    PRE_DISPLAY_SIZE_CODE = 13
    DISPLAY_WIDTH_CODE = 14
    DISPLAY_INDENT_CODE = 15
    OVERFULL_RULE_CODE = 16
    HANG_INDENT_CODE = 17
    H_OFFSET_CODE = 18
    V_OFFSET_CODE = 19
    EMERGENCY_STRETCH_CODE = 20
    PDFTEX_FIRST_DIMEN_CODE = 21
    PDF_H_ORIGIN_CODE = PDFTEX_FIRST_DIMEN_CODE + 0
    PDF_V_ORIGIN_CODE = PDFTEX_FIRST_DIMEN_CODE + 1
    PDF_PAGE_WIDTH_CODE = PDFTEX_FIRST_DIMEN_CODE + 2
    PDF_PAGE_HEIGHT_CODE = PDFTEX_FIRST_DIMEN_CODE + 3
    PDF_LINK_MARGIN_CODE = PDFTEX_FIRST_DIMEN_CODE + 4
    PDF_DEST_MARGIN_CODE = PDFTEX_FIRST_DIMEN_CODE + 5
    PDF_THREAD_MARGIN_CODE = PDFTEX_FIRST_DIMEN_CODE + 6
    PDF_FIRST_LINE_HEIGHT_CODE = PDFTEX_FIRST_DIMEN_CODE + 7
    PDF_LAST_LINE_DEPTH_CODE = PDFTEX_FIRST_DIMEN_CODE + 8
    PDF_EACH_LINE_HEIGHT_CODE = PDFTEX_FIRST_DIMEN_CODE + 9
    PDF_EACH_LINE_DEPTH_CODE = PDFTEX_FIRST_DIMEN_CODE + 10
    PDF_IGNORED_DIMEN_CODE = PDFTEX_FIRST_DIMEN_CODE + 11
    PDF_PX_DIMEN_CODE = PDFTEX_FIRST_DIMEN_CODE + 12
    PDFTEX_LAST_DIMEN_CODE = PDFTEX_FIRST_DIMEN_CODE + 12
    DIMEN_PARS = PDFTEX_LAST_DIMEN_CODE + 1
    SCALED_BASE = DIMEN_BASE + DIMEN_PARS
    EQTB_SIZE = SCALED_BASE + 255

    # {275}:
    PRIM_SIZE = 2100
    PRIM_PRIME = 1777
    PRIM_BASE = 1
    UNDEFINED_PRIMITIVE = 0

    # {290}:
    RESTORE_OLD_VALUE = 0
    RESTORE_ZERO = 1
    INSERT_TOKEN = 2
    LEVEL_BOUNDARY = 3
    RESTORE_SA = 4

    # {291}:
    BOTTOM_LEVEL = 0
    SIMPLE_GROUP = 1
    HBOX_GROUP = 2
    ADJUSTED_HBOX_GROUP = 3
    VBOX_GROUP = 4
    VTOP_GROUP = 5
    ALIGN_GROUP = 6
    NO_ALIGN_GROUP = 7
    OUTPUT_GROUP = 8
    MATH_GROUP = 9
    DISC_GROUP = 10
    INSERT_GROUP = 11
    VCENTER_GROUP = 12
    MATH_CHOICE_GROUP = 13
    SEMI_SIMPLE_GROUP = 14
    MATH_SHIFT_GROUP = 15
    MATH_LEFT_GROUP = 16
    MAX_GROUP_CODE = 16

    # {311}:
    CS_TOKEN_FLAG = 07777
    LEFT_BRACE_TOKEN = 0400
    LEFT_BRACE_LIMIT = 01000
    RIGHT_BRACE_TOKEN = 01000
    RIGHT_BRACE_LIMIT = 01400
    MATH_SHIFT_TOKEN = 01400
    TAB_TOKEN = 02000
    OUT_PARAM_TOKEN = 02400
    SPACE_TOKEN = 05040
    LETTER_TOKEN = 05400
    OTHER_TOKEN = 06000
    MATCH_TOKEN = 06400
    END_MATCH_TOKEN = 07000
    PROTECTED_TOKEN = 07001

    # {325}:
    MID_LINE = 1
    SKIP_BLANKS = 2 + MAX_CHAR_CODE
    NEW_LINE = 3 + MAX_CHAR_CODE + MAX_CHAR_CODE

    # {327}:
    SKIPPING = 1
    DEFINING = 2
    MATCHING = 3
    ALIGNING = 4
    ABSORBING = 5

    # {329}:
    TOKEN_LIST = 0
    PARAMETER = 0
    U_TEMPLATE = 1
    V_TEMPLATE = 2
    BACKED_UP = 3
    INSERTED = 4
    MACRO = 5
    OUTPUT_TEXT = 6
    EVERY_PAR_TEXT = 7
    EVERY_MATH_TEXT = 8
    EVERY_DISPLAY_TEXT = 9
    EVERY_HBOX_TEXT = 10
    EVERY_VBOX_TEXT = 11
    EVERY_JOB_TEXT = 12
    EVERY_CR_TEXT = 13
    MARK_TEXT = 14
    ETEX_TEXT_OFFSET = OUTPUT_ROUTINE_LOC - OUTPUT_TEXT
    EVERY_EOF_TEXT = EVERY_EOF_LOC - ETEX_TEXT_OFFSET
    WRITE_TEXT = TOKS_BASE - ETEX_TEXT_OFFSET

    # {380}:
    NO_EXPAND_FLAG = 257

    # {411}:
    MARKS_CODE = 5
    TOP_MARK_CODE = 0
    FIRST_MARK_CODE = 1
    BOT_MARK_CODE = 2
    SPLIT_FIRST_MARK_CODE = 3
    SPLIT_BOT_MARK_CODE = 4

    # {439}:
    INT_VAL = 0
    DIMEN_VAL = 1
    GLUE_VAL = 2
    MU_VAL = 3
    IDENT_VAL = 4
    TOK_VAL = 5

    # {445}:
    LAST_NODE_TYPE_CODE = GLUE_VAL + 1
    INPUT_LINE_NO_CODE = GLUE_VAL + 2
    BADNESS_CODE = INPUT_LINE_NO_CODE + 1
    PDFTEX_FIRST_RINT_CODE = BADNESS_CODE + 1
    PDFTEX_VERSION_CODE = PDFTEX_FIRST_RINT_CODE + 0
    PDF_LAST_OBJ_CODE = PDFTEX_FIRST_RINT_CODE + 1
    PDF_LAST_XFORM_CODE = PDFTEX_FIRST_RINT_CODE + 2
    PDF_LAST_XIMAGE_CODE = PDFTEX_FIRST_RINT_CODE + 3
    PDF_LAST_XIMAGE_PAGES_CODE = PDFTEX_FIRST_RINT_CODE + 4
    PDF_LAST_ANNOT_CODE = PDFTEX_FIRST_RINT_CODE + 5
    PDF_LAST_X_POS_CODE = PDFTEX_FIRST_RINT_CODE + 6
    PDF_LAST_Y_POS_CODE = PDFTEX_FIRST_RINT_CODE + 7
    PDF_RETVAL_CODE = PDFTEX_FIRST_RINT_CODE + 8
    PDF_LAST_XIMAGE_COLORDEPTH_CODE = PDFTEX_FIRST_RINT_CODE + 9
    ELAPSED_TIME_CODE = PDFTEX_FIRST_RINT_CODE + 10
    PDF_SHELL_ESCAPE_CODE = PDFTEX_FIRST_RINT_CODE + 11
    RANDOM_SEED_CODE = PDFTEX_FIRST_RINT_CODE + 12
    PDF_LAST_LINK_CODE = PDFTEX_FIRST_RINT_CODE + 13
    PDFTEX_LAST_ITEM_CODES = PDFTEX_FIRST_RINT_CODE + 13
    ETEX_INT = PDFTEX_LAST_ITEM_CODES + 1
    ETEX_DIM = ETEX_INT + 8
    ETEX_GLUE = ETEX_DIM + 9
    ETEX_MU = ETEX_GLUE + 1
    ETEX_EXPR = ETEX_MU + 1

    # {450}:
    MAX_DIMEN = 07777777777

    # {467}:
    OCTAL_TOKEN = OTHER_TOKEN + "'".ord
    HEX_TOKEN = OTHER_TOKEN + "\"".ord
    ALPHA_TOKEN = OTHER_TOKEN + "`".ord
    POINT_TOKEN = OTHER_TOKEN + ".".ord
    CONTINENTAL_POINT_TOKEN = OTHER_TOKEN + ",".ord

    # {492}:
    DEFAULT_RULE = 26214

    # {497}:
    NUMBER_CODE = 0
    ROMAN_NUMERAL_CODE = 1
    STRING_CODE = 2
    MEANING_CODE = 3
    FONT_NAME_CODE = 4
    ETEX_CONVERT_BASE = 5
    ETEX_REVISION_CODE = ETEX_CONVERT_BASE
    ETEX_CONVERT_CODES = ETEX_CONVERT_BASE + 1
    PDFTEX_FIRST_EXPAND_CODE = ETEX_CONVERT_CODES
    PDFTEX_REVISION_CODE = PDFTEX_FIRST_EXPAND_CODE + 0
    PDFTEX_BANNER_CODE = PDFTEX_FIRST_EXPAND_CODE + 1
    PDF_FONT_NAME_CODE = PDFTEX_FIRST_EXPAND_CODE + 2
    PDF_FONT_OBJNUM_CODE = PDFTEX_FIRST_EXPAND_CODE + 3
    PDF_FONT_SIZE_CODE = PDFTEX_FIRST_EXPAND_CODE + 4
    PDF_PAGE_REF_CODE = PDFTEX_FIRST_EXPAND_CODE + 5
    PDF_XFORM_NAME_CODE = PDFTEX_FIRST_EXPAND_CODE + 6
    PDF_ESCAPE_STRING_CODE = PDFTEX_FIRST_EXPAND_CODE + 7
    PDF_ESCAPE_NAME_CODE = PDFTEX_FIRST_EXPAND_CODE + 8
    LEFT_MARGIN_KERN_CODE = PDFTEX_FIRST_EXPAND_CODE + 9
    RIGHT_MARGIN_KERN_CODE = PDFTEX_FIRST_EXPAND_CODE + 10
    PDF_STRCMP_CODE = PDFTEX_FIRST_EXPAND_CODE + 1
    PDF_COLORSTACK_INIT_CODE = PDFTEX_FIRST_EXPAND_CODE + 12
    PDF_ESCAPE_HEX_CODE = PDFTEX_FIRST_EXPAND_CODE + 13
    PDF_UNESCAPE_HEX_CODE = PDFTEX_FIRST_EXPAND_CODE + 14
    PDF_CREATION_DATE_CODE = PDFTEX_FIRST_EXPAND_CODE + 15
    PDF_FILE_MOD_DATE_CODE = PDFTEX_FIRST_EXPAND_CODE + 16
    PDF_FILE_SIZE_CODE = PDFTEX_FIRST_EXPAND_CODE + 17
    PDF_MDFIVE_SUM_CODE = PDFTEX_FIRST_EXPAND_CODE + 18
    PDF_FILE_DUMP_CODE = PDFTEX_FIRST_EXPAND_CODE + 19
    PDF_MATCH_CODE = PDFTEX_FIRST_EXPAND_CODE + 20
    PDF_LAST_MATCH_CODE = PDFTEX_FIRST_EXPAND_CODE + 21
    UNIFORM_DEVIATE_CODE = PDFTEX_FIRST_EXPAND_CODE + 22
    NORMAL_DEVIATE_CODE = PDFTEX_FIRST_EXPAND_CODE + 23
    PDF_INSERT_HT_CODE = PDFTEX_FIRST_EXPAND_CODE + 24
    PDF_XIMAGE_BBOX_CODE = PDFTEX_FIRST_EXPAND_CODE + 25
    PDFTEX_CONVERT_CODES = PDFTEX_FIRST_EXPAND_CODE + 26
    JOB_NAME_CODE = PDFTEX_CONVERT_CODES

    # {509}:
    CLOSED = 2
    JUST_OPEN = 1

    # {516}:
    UNLESS_CODE = 32
    IF_CHAR_CODE = 0
    IF_CAT_CODE = 1
    IF_INT_CODE = 2
    IF_DIM_CODE = 3
    IF_ODD_CODE = 4
    IF_VMODE_CODE = 5
    IF_HMODE_CODE = 6
    IF_MMODE_CODE = 7
    IF_INNER_CODE = 8
    IF_VOID_CODE = 9
    IF_HBOX_CODE = 10
    IF_VBOX_CODE = 11
    IFX_CODE = 12
    IF_EOF_CODE = 13
    IF_TRUE_CODE = 14
    IF_FALSE_CODE = 15
    IF_CASE_CODE = 16
    IF_PDFPRIMITIVE_CODE = 21

    # {518}:
    IF_NODE_SIZE = 2
    IF_CODE = 1
    FI_CODE = 2
    ELSE_CODE = 3
    OR_CODE = 4

    # {549*}:
    FORMAT_AREA_LENGTH = 0
    FORMAT_EXT_LENGTH = 4
    FORMAT_EXTENSION = ".fmt"

    # {573}:
    NO_TAG = 0
    LIG_TAG = 1
    LIST_TAG = 2
    EXT_TAG = 3

    # {576}:
    SLANT_CODE = 1
    SPACE_CODE = 2
    SPACE_STRETCH_CODE = 3
    SPACE_SHRINK_CODE = 4
    X_HEIGHT_CODE = 5
    QUAD_CODE = 6
    EXTRA_SPACE_CODE = 7

    # {578*}:
    NON_ADDRESS = 0

    # {586}:
    KERN_BASE_OFFSET = 256*(128 + MIN_QUARTERWORD)

    # {616}:
    SET_CHAR_0 = 0
    SET1 = 128
    SET_RULE = 132
    PUT_RULE = 137
    NOP = 138
    BOP = 139
    EOP = 140
    PUSH = 141
    POP = 142
    RIGHT1 = 143
    W0 = 147
    W1 = 148
    X0 = 152
    X1 = 153
    DOWN1 = 157
    Y0 = 161
    Y1 = 162
    Z0 = 166
    Z1 = 167
    FNT_NUM_0 = 171
    FNT1 = 235
    XXX1 = 239
    XXX4 = 242
    FNT_DEF1 = 243
    PRE = 247
    POST = 248
    POST_POST = 249

    # {617}:
    ID_BYTE = 2

    # {635}:
    MOVEMENT_NODE_SIZE = 3

    # {638}:
    Y_HERE = 1
    Z_HERE = 2
    YZ_OK = 3
    Y_OK = 4
    Z_OK = 5
    D_FIXED = 6

    # {641}:
    NONE_SEEN = 0
    Y_SEEN = 6
    Z_SEEN = 12

    # {646}:
    REVERSED = 1
    DLIST = 2
    LEFT_TO_RIGHT = 0
    RIGHT_TO_LEFT = 1

    # {650*}:
    MOVE_PAST = 13
    FIN_RULE = 14
    NEXT_P = 15

    # {656}:
    BILLION = 1000000000.0

    # {678}:
    INF_PDF_MEM_SIZE = 10000
    SUP_PDF_MEM_SIZE = 10000000

    # {682}:
    PDF_OP_BUF_SIZE = 16384
    INF_PDF_OS_BUF_SIZE = 1
    SUP_PDF_OS_BUF_SIZE = 5000000
    PDF_OS_MAX_OBJS = 100

    # {683}:
    NO_ZIP = 0
    ZIP_WRITING = 1
    ZIP_FINISH = 2

    # {689}:
    PDF_NEW_LINE_CHAR = 10

    # {690}:
    MAX_INTEGER = 0x7FFFFFFF

    # {699}:
    OBJ_TYPE_OTHERS = 0
    OBJ_TYPE_PAGE = 1
    OBJ_TYPE_PAGES = 2
    OBJ_TYPE_FONT = 3
    OBJ_TYPE_OUTLINE = 4
    OBJ_TYPE_DEST = 5
    OBJ_TYPE_OBJ = 6
    OBJ_TYPE_XFORM = 7
    OBJ_TYPE_XIMAGE = 8
    OBJ_TYPE_THREAD = 9
    HEAD_TAB_MAX = OBJ_TYPE_THREAD
    PAGES_TREE_KIDS_MAX = 6
    NAME_TREE_KIDS_MAX  = 6
    SET_ORIGIN = 0
    DIRECT_PAGE = 1
    DIRECT_ALWAYS = 2
    SCAN_SPECIAL = 3
    PDF_COLORSTACK_NODE_SIZE = 3
    PDF_COLORSTACK_SETTER_NODE_SIZE = 3
    PDF_COLORSTACK_GETTER_NODE_SIZE = 2
    COLORSTACK_SET = 0
    COLORSTACK_PUSH = 1
    COLORSTACK_DATA = 1
    COLORSTACK_POP = 2
    COLORSTACK_CURRENT = 3
    PDF_SETMATRIX_NODE_SIZE = 2
    PDF_SAVE_NODE_SIZE = 2
    PDF_RESTORE_NODE_SIZE = 2
    PDF_REFOBJ_NODE_SIZE = 2
    PDFMEM_OBJ_SIZE = 4
    PDF_REFXFORM_NODE_SIZE = 5
    PDFMEM_XFORM_SIZE = 6
    PDF_REFXIMAGE_NODE_SIZE = 5
    PDFMEM_XIMAGE_SIZE = 5
    PDF_ANNOT_NODE_SIZE = 7
    PDF_ACTION_PAGE = 0
    PDF_ACTION_GOTO = 1
    PDF_ACTION_THREAD = 2
    PDF_ACTION_USER = 3
    PDF_ACTION_SIZE = 3
    PDFMEM_OUTLINE_SIZE = 8
    PDF_DEST_XYZ = 0
    PDF_DEST_FIT = 1
    PDF_DEST_FITH = 2
    PDF_DEST_FITV = 3
    PDF_DEST_FITB = 4
    PDF_DEST_FITBH = 5
    PDF_DEST_FITBV = 6
    PDF_DEST_FITR = 7
    PDF_DEST_NODE_SIZE = 7
    PDF_THREAD_NODE_SIZE = 7
    PDFMEM_BEAD_SIZE = 5
    SNAP_NODE_SIZE = 3
    INF_OBJ_TAB_SIZE = 1000
    SUP_OBJ_TAB_SIZE = 8388607
    INF_DEST_NAMES_SIZE = 1000
    SUP_DEST_NAMES_SIZE = 500000
    INF_PK_DPI = 72
    SUP_PK_DPI = 8000
    PDF_OBJTYPE_MAX = HEAD_TAB_MAX

    # {707}:
    NEW_FONT_TYPE = 0
    VIRTUAL_FONT_TYPE = 1
    REAL_FONT_TYPE = 2
    SUBST_FONT_TYPE = 3

    # {709}:
    NON_EXISTENT_PATH = "///..."

    # {714}:
    VF_MAX_PACKET_LENGTH = 10000
    DO_CHAR = 70
    LONG_CHAR = 242
    VF_ID = 202
    PUT1 = 133

    # {725}:
    VF_MAX_RECURSION = 10
    VF_STACK_SIZE = 100

    # {818}:
    EXACTLY = 0
    ADDITIONAL = 1

    # {825}:
    CAL_EXPAND_RATIO = 2
    SUBST_EX_FONT = 3
    SUBSTITUTED = 3

    # {859}:
    NOAD_SIZE = 4
    MATH_CHAR = 1
    SUB_BOX = 2
    SUB_MLIST = 3
    MATH_TEXT_CHAR = 4

    # {860}:
    ORD_NOAD = UNSET_NODE + 3
    OP_NOAD = ORD_NOAD + 1
    BIN_NOAD = ORD_NOAD + 2
    REL_NOAD = ORD_NOAD + 3
    OPEN_NOAD = ORD_NOAD + 4
    CLOSE_NOAD = ORD_NOAD + 5
    PUNCT_NOAD = ORD_NOAD + 6
    INNER_NOAD = ORD_NOAD + 7
    LIMITS = 1
    NO_LIMITS = 2

    # {861}:
    RADICAL_NOAD = INNER_NOAD + 1
    RADICAL_NOAD_SIZE = 5
    FRACTION_NOAD = RADICAL_NOAD + 1
    FRACTION_NOAD_SIZE = 6
    DEFAULT_CODE = 010000000000

    # {865}:
    UNDER_NOAD = FRACTION_NOAD + 1
    OVER_NOAD = UNDER_NOAD + 1
    ACCENT_NOAD = OVER_NOAD + 1
    ACCENT_NOAD_SIZE = 5
    VCENTER_NOAD = ACCENT_NOAD + 1
    LEFT_NOAD = VCENTER_NOAD + 1
    RIGHT_NOAD = LEFT_NOAD + 1
    MIDDLE_NOAD = 1

    # {866}:
    STYLE_NODE = UNSET_NODE + 1
    STYLE_NODE_SIZE = 3
    DISPLAY_STYLE = 0
    TEXT_STYLE = 2
    SCRIPT_STYLE = 4
    SCRIPT_SCRIPT_STYLE = 6
    CRAMPED = 1

    # {867}:
    CHOICE_NODE = UNSET_NODE + 2

    # {877}:
    TEXT_SIZE = 0
    SCRIPT_SIZE = 16
    SCRIPT_SCRIPT_SIZE = 32

    # {878}:
    TOTAL_MATHSY_PARAMS = 22

    # {879}:
    TOTAL_MATHEX_PARAMS = 13

    # {942}:
    MATH_SPACING = \
      "0234000122*4000133**3**344*0400400*000000234000111*1111112341011"

    # {948}:
    ALIGN_STACK_NODE_SIZE = 6

    # {958}:
    SPAN_CODE = 256
    CR_CODE = 257
    CR_CR_CODE = CR_CODE + 1
    END_TEMPLATE_TOKEN = CS_TOKEN_FLAG + FROZEN_END_TEMPLATE

    # {975}:
    SPAN_NODE_SIZE = 2

    # {995}:
    TIGHT_FIT = 3
    LOOSE_FIT = 1
    VERY_LOOSE_FIT = 0
    DECENT_FIT = 2

    # {997}:
    ACTIVE_NODE_SIZE_NORMAL = 3
    UNHYPHENATED = 0
    HYPHENATED = 1

    # {999}:
    PASSIVE_NODE_SIZE = 2

    # {1000}:
    DELTA_NODE_SIZE = 9
    DELTA_NODE = 2

    # {1011}:
    AWFUL_BAD = 07777777777

    # {1153}:
    DEPLORABLE = 100000

    # {1159}:
    INSERTS_ONLY = 1
    BOX_THERE = 2

    # {1160}:
    PAGE_INS_NODE_SIZE = 4
    INSERTING = 0
    SPLIT_UP = 1

    # {1238}:
    FIL_CODE = 0
    FILL_CODE = 1
    SS_CODE = 2
    FIL_NEG_CODE = 3
    SKIP_CODE = 4
    MSKIP_CODE = 5

    # {1251}:
    BOX_FLAG = 010000000000
    GLOBAL_BOX_FLAG = 010000100000
    SHIP_OUT_FLAG = 010000200000
    LEADER_FLAG = 010000200001
    BOX_CODE = 0
    COPY_CODE = 1
    LAST_BOX_CODE = 2
    VSPLIT_CODE = 3
    VTOP_CODE = 4

    # {1358}:
    ABOVE_CODE = 0
    OVER_CODE = 1
    ATOP_CODE = 2
    DELIMITED_CODE = 3

    # {1402*}:
    CHAR_DEF_CODE = 0
    MATH_CHAR_DEF_CODE = 1
    COUNT_DEF_CODE = 2
    DIMEN_DEF_CODE = 3
    SKIP_DEF_CODE = 4
    MU_SKIP_DEF_CODE = 5
    TOKS_DEF_CODE = 6
    CHAR_SUB_DEF_CODE = 7

    # {1471}:
    SHOW_CODE = 0
    SHOW_BOX_CODE = 1
    SHOW_THE_CODE = 2
    SHOW_LISTS = 3

    # {1523*}:
    WRITE_NODE_SIZE = 2
    OPEN_NODE_SIZE = 3
    OPEN_NODE = 0
    WRITE_NODE = 1
    CLOSE_NODE = 2
    SPECIAL_NODE = 3
    LANGUAGE_NODE = 4
    MUBYTE_ZERO = 64

    # {1526*}:
    IMMEDIATE_CODE = 4
    SET_LANGUAGE_CODE = 5
    PDFTEX_FIRST_EXTENSION_CODE = 6
    PDF_LITERAL_NODE = PDFTEX_FIRST_EXTENSION_CODE + 0
    PDF_OBJ_CODE = PDFTEX_FIRST_EXTENSION_CODE + 1
    PDF_REFOBJ_NODE = PDFTEX_FIRST_EXTENSION_CODE + 2
    PDF_XFORM_CODE = PDFTEX_FIRST_EXTENSION_CODE + 3
    PDF_REFXFORM_NODE = PDFTEX_FIRST_EXTENSION_CODE + 4
    PDF_XIMAGE_CODE = PDFTEX_FIRST_EXTENSION_CODE + 5
    PDF_REFXIMAGE_NODE = PDFTEX_FIRST_EXTENSION_CODE + 6
    PDF_ANNOT_NODE = PDFTEX_FIRST_EXTENSION_CODE + 7
    PDF_START_LINK_NODE = PDFTEX_FIRST_EXTENSION_CODE + 8
    PDF_END_LINK_NODE = PDFTEX_FIRST_EXTENSION_CODE + 9
    PDF_OUTLINE_CODE = PDFTEX_FIRST_EXTENSION_CODE + 10
    PDF_DEST_NODE = PDFTEX_FIRST_EXTENSION_CODE + 11
    PDF_THREAD_NODE = PDFTEX_FIRST_EXTENSION_CODE + 12
    PDF_START_THREAD_NODE = PDFTEX_FIRST_EXTENSION_CODE + 13
    PDF_END_THREAD_NODE = PDFTEX_FIRST_EXTENSION_CODE + 14
    PDF_SAVE_POS_NODE = PDFTEX_FIRST_EXTENSION_CODE + 15
    PDF_INFO_CODE = PDFTEX_FIRST_EXTENSION_CODE + 16
    PDF_CATALOG_CODE = PDFTEX_FIRST_EXTENSION_CODE + 17
    PDF_NAMES_CODE = PDFTEX_FIRST_EXTENSION_CODE + 18
    PDF_FONT_ATTR_CODE = PDFTEX_FIRST_EXTENSION_CODE + 19
    PDF_INCLUDE_CHARS_CODE = PDFTEX_FIRST_EXTENSION_CODE + 20
    PDF_MAP_FILE_CODE = PDFTEX_FIRST_EXTENSION_CODE + 21
    PDF_MAP_LINE_CODE = PDFTEX_FIRST_EXTENSION_CODE + 22
    PDF_TRAILER_CODE = PDFTEX_FIRST_EXTENSION_CODE + 23
    RESET_TIMER_CODE = PDFTEX_FIRST_EXTENSION_CODE + 24
    PDF_FONT_EXPAND_CODE = PDFTEX_FIRST_EXTENSION_CODE + 25
    SET_RANDOM_SEED_CODE = PDFTEX_FIRST_EXTENSION_CODE + 26
    PDF_SNAP_REF_POINT_NODE = PDFTEX_FIRST_EXTENSION_CODE + 27
    PDF_SNAPY_NODE = PDFTEX_FIRST_EXTENSION_CODE + 28
    PDF_SNAPY_COMP_NODE = PDFTEX_FIRST_EXTENSION_CODE + 29
    PDF_GLYPH_TO_UNICODE_CODE = PDFTEX_FIRST_EXTENSION_CODE + 30
    PDF_COLORSTACK_NODE = PDFTEX_FIRST_EXTENSION_CODE + 31
    PDF_SETMATRIX_NODE = PDFTEX_FIRST_EXTENSION_CODE + 32
    PDF_SAVE_NODE = PDFTEX_FIRST_EXTENSION_CODE + 33
    PDF_RESTORE_NODE = PDFTEX_FIRST_EXTENSION_CODE + 34
    PDF_NOBUILTIN_TOUNICODE_CODE = PDFTEX_FIRST_EXTENSION_CODE + 35
    PDFTEX_LAST_EXTENSION_CODE = PDFTEX_FIRST_EXTENSION_CODE + 35

    # {1613}:
    END_WRITE_TOKEN = CS_TOKEN_FLAG + END_WRITE

    # {1626}:
    PDF_MAX_LINK_LEVEL = 10

    # {1644}:
    ETEX_STATE_BASE = INT_BASE + ETEX_STATE_CODE
    ETEX_VERSION_CODE = ETEX_INT

    # {1658}:
    CURRENT_GROUP_LEVEL_CODE = ETEX_INT + 1
    CURRENT_GROUP_TYPE_CODE = ETEX_INT + 2

    # {1661}:
    CURRENT_IF_LEVEL_CODE = ETEX_INT + 3
    CURRENT_IF_TYPE_CODE = ETEX_INT + 4
    CURRENT_IF_BRANCH_CODE = ETEX_INT + 5

    # {1664}:
    FONT_CHAR_WD_CODE = ETEX_DIM
    FONT_CHAR_HT_CODE = ETEX_DIM + 1
    FONT_CHAR_DP_CODE = ETEX_DIM + 2
    FONT_CHAR_IC_CODE = ETEX_DIM + 3

    # {1667}:
    PAR_SHAPE_LENGTH_CODE = ETEX_DIM + 4
    PAR_SHAPE_INDENT_CODE = ETEX_DIM + 5
    PAR_SHAPE_DIMEN_CODE = ETEX_DIM + 6

    # {1670}:
    SHOW_GROUPS = 4

    # {1679}:
    SHOW_TOKENS = 5

    # {1684}:
    SHOW_IFS = 6

    # {1714}:
    EDGE_NODE = STYLE_NODE
    EDGE_NODE_SIZE = STYLE_NODE_SIZE

    # {1757}:
    IF_DEF_CODE = 17
    IF_CS_CODE = 18
    IF_FONT_CHAR_CODE = 19
    IF_IN_CSNAME_CODE = 20
    IF_PDFABS_NUM_CODE = 22
    IF_PDFABS_DIM_CODE = 23

    # {1778}:
    EXPR_NONE = 0
    EXPR_ADD = 1
    EXPR_SUB = 2
    EXPR_MULT = 3
    EXPR_DIV = 4
    EXPR_SCALE = 5

    # {1783}:
    EXPR_NODE_SIZE = 4

    # {1796}:
    GLUE_STRETCH_ORDER_CODE = ETEX_INT + 6
    GLUE_SHRINK_ORDER_CODE = ETEX_INT + 7
    GLUE_STRETCH_CODE = ETEX_DIM + 7
    GLUE_SHRINK_CODE = ETEX_DIM + 8

    # {1800}:
    MU_TO_GLUE_CODE = ETEX_GLUE
    GLUE_TO_MU_CODE = ETEX_MU

    # {1810}:
    BOX_VAL = 4
    MARK_VAL = 6
    DIMEN_VAL_LIMIT = 0x20
    MU_VAL_LIMIT = 0x40
    BOX_VAL_LIMIT = 0x50
    TOK_VAL_LIMIT = 0x60
    INDEX_NODE_SIZE = 9

    # {1815}:
    POINTER_NODE_SIZE = 2
    WORD_NODE_SIZE = 3
    MARK_CLASS_NODE_SIZE = 4

    # {1820}:
    VSPLIT_INIT = 0
    FIRE_UP_INIT = 1
    FIRE_UP_DONE = 2
    DESTROY_MARKS = 3

    # {1837}:
    ACTIVE_NODE_SIZE_EXTENDED = 5

    # {1885*}:
    ENCTEX_BANNER = " encTeX v. Jun. 2004"

    # Other constants:
    IMAGE_TYPE_NONE = 0
    IMAGE_TYPE_PDF = 1
    IMAGE_TYPE_PNG = 2
    IMAGE_TYPE_JPG = 3
    IMAGE_TYPE_TIF = 4
    IMAGE_TYPE_JBIG2 = 5

    IMAGE_COLOR_B = 1
    IMAGE_COLOR_C = 2
    IMAGE_COLOR_I = 4
  end

end
